version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.1.0-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --endpoints
      - "endpoints.yml"
  app:
    image: gusmcarreira/chatbot_actions:3.1.0
    expose:
      - 5055